spring.application.name=finance-project
spring.datasource.url=jdbc:postgresql://localhost:5432/TradeX
spring.datasource.username=postgres
spring.datasource.password=270406

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true