spring.application.name=finance-project
security.jwt.secret=${JWT_SECRET:8f4Kx9Qv2Lm7Tz1Np6Rc3Yw8Hs5Ua0Ee4Jk9Bx7Vm2Qp6Nd1Wr8Tf3Zx5Cg0Ls9}
spring.datasource.url=jdbc:postgresql://localhost:5432/TradeX
spring.datasource.username=postgres
spring.datasource.password=270406

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true 